require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'vervitudeconsultants' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'vervitudeconsultantsTests' do
    inherit! :complete
    # Pods for testing
  end
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  
  # flipper_post_install(installer)

end
pod 'Firebase/Analytics'
pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"

target 'vervitudeconsultants-tvOS' do
  # Pods for vervitudeconsultants-tvOS

  target 'vervitudeconsultants-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

